# Generated by Django 2.1.7 on 2020-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='UR',
            field=models.CharField(default='', max_length=200),
        ),
    ]
