# Generated by Django 2.1.7 on 2020-06-01 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0002_file_ur'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
