# Generated by Django 2.1.7 on 2020-06-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0003_auto_20200601_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='credit',
            new_name='Credit',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='debit',
            new_name='Debit',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Index',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.AddField(
            model_name='file',
            name='Date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
