# Generated by Django 2.1.7 on 2020-06-01 16:33

from django.db import migrations
import djongo.models.fields
import pdfupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0004_auto_20200601_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Debit',
        ),
        migrations.RemoveField(
            model_name='file',
            name='Description',
        ),
        # migrations.AddField(
        #     model_name='file',
        #     name='DataSaved',
        #     field=djongo.models.fields.ArrayField(default=0, model_container=pdfupload.models.Data, model_form_class=pdfupload.models.DataForm),
        # ),
    ]
