# Generated by Django 2.1.7 on 2020-06-01 16:57

from django.db import migrations
import djongo.models.fields
import pdfupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0005_auto_20200601_2203'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='file',
        #     name='blog',
        #     field=djongo.models.fields.EmbeddedField(model_container=pdfupload.models.Blog, model_form_class=pdfupload.models.BlogForm, null=True),
        # ),
    ]
