# Generated by Django 2.1.7 on 2020-06-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0006_file_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='Date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='Debit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='Description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
