# Generated by Django 2.1.7 on 2020-06-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0007_auto_20200602_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
