# Generated by Django 2.1.7 on 2020-06-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0009_dicty_keyval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.CharField(max_length=240),
        ),
    ]
