# Generated by Django 2.1.7 on 2020-06-05 12:09

from django.db import migrations, models
import djongo.models.fields
import pdfupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfupload', '0010_auto_20200605_1727'),
    ]

    operations = [
        #migrations.CreateModel(
        #     name='File',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('UR', models.CharField(default='', max_length=200)),
        #         ('DataSaved', djongo.models.fields.ArrayField(default=[0], model_container=pdfupload.models.Data, model_form_class=pdfupload.models.DataForm)),
        #     ],
        # ),
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
