# Generated by Django 2.1.7 on 2020-06-05 12:27

from django.db import migrations, models
import djongo.models.fields
import pdfupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdfupload', '0011_auto_20200605_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('blog', djongo.models.fields.EmbeddedField(model_container=pdfupload.models.Blog, model_form_class=pdfupload.models.BlogForm, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('authors', djongo.models.fields.ArrayField(model_container=pdfupload.models.Author, model_form_class=pdfupload.models.AuthorForm)),
            ],
        ),
    ]
